version: '2'

services:
    reviews:
        build:
            context: .
        image: weaveworksdemos/reviews
        hostname: reviews
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        environment:
            - MONGO_HOST=reviews-db:27017
            - reschedule=on-node-failure
        ports:
            - "8080:80"
    reviews-db:
        build:
            context: ./docker/reviews-db/
        image: weaveworksdemos/reviews-db
        hostname: reviews-db
        restart: always
        cap_drop:
            - all
        cap_add:
            - CHOWN
            - SETGID
            - SETUID
        read_only: true
        tmpfs:
            - /tmp:rw,noexec,nosuid
        environment:
            - reschedule=on-node-failure
        ports:
            - "27017:27017"
