version: '2'

services:
    reviews:
        build:
            context: .
            dockerfile: ./docker/reviews/Dockerfile
        image: weaveworksdemos/reviews
        hostname: reviews
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        environment:
            - reschedule=on-node-failure
        ports:
            - "8080:80"
    reviews-db:
        build:
            context: ./docker/reviews-db/
        image: weaveworksdemos/reviews-db
        hostname: reviews-db
        restart: always
        environment:
            - reschedule=on-node-failure
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=socksdb
