FROM golang:1.22-alpine

COPY . /go/src/github.com/ftuyama/reviews-microservice/
WORKDIR /go/src/github.com/ftuyama/reviews-microservice/

RUN apk update
RUN apk add git
RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o /reviews main.go

FROM alpine:3.4

ENV	SERVICE_USER=myuser \
	SERVICE_UID=10001 \
	SERVICE_GROUP=mygroup \
	SERVICE_GID=10001

RUN	addgroup -g ${SERVICE_GID} ${SERVICE_GROUP} && \
	adduser -g "${SERVICE_NAME} user" -D -H -G ${SERVICE_GROUP} -s /sbin/nologin -u ${SERVICE_UID} ${SERVICE_USER}

ENV HATEAOS reviews
ENV USER_DATABASE mongodb
ENV MONGO_HOST reviews-db

WORKDIR /
EXPOSE 8080
COPY --from=0 /reviews /

RUN	chmod +x /reviews && \
	chown -R ${SERVICE_USER}:${SERVICE_GROUP} /reviews

USER ${SERVICE_USER}

CMD ["/reviews", "-port=8080"]
